### ISSUE TITLE
Problem with nodeSelection_1.py

### ISSUE THREAD

**Issue by renno-bih** [cristian-frincu/navigation_waypoints_scripts#2]
Hi, 
thanks for sharing this project. It is very educational :)

I'm having problem generating X and Y coordinates using nodeSelection_1.py script.
When I select few points they are correctly printed in console but waypointNodesc.csv contains only last coordinate.
I also tried manually to enter coordinates and run simulation but looks like coordinates selected on nodeSelection_1.py don't match map RViz.

Any hints?

**Comment by cristian-frincu** [comment]
Hi, 
The .csv files need to deleted in between each run (if you would like to update the scripts i can accept the pull) so that is why you might be getting different coordinates showing up, from previous runs. Also it could be that your map and navagiation are expecting coordinates on different frames.

Regarding only the last coordinate showing in the csv, I did not have that problem before. Try having the csv file there, but just empty, and see if that might fix it?
The script is quite simple so you could play around with it to make changes

**Comment by renno-bih** [comment]
Hi Cristian,

problem was with mode for writing to file. I replaced `"w+"` with `"a"`
`f = file("waypointNodes.csv","a")`
With append parameter it successfully adds all waypoints, not only last one.

Second problem was related to transforming pixels to real dimensions. 
As my map is with different resolution I had to change it in `nodeSelection_1.py`
Replaced this:
```
x_transform = (x)*(0.02) - 10
y_transform = (y)*(-0.02) + 10
```
With following:
```
x_transform = (x)*(0.05) - 10
y_transform = (y)*(-0.05) + 9.2
```

Replacing resolution parameter was logical but I have no idea why Y axis is shifted for 0.8.
But it all works now, thanks :)
